### ISSUE TITLE
TBA instructor has a RateMyProf section

### ISSUE THREAD

**Issue by Jasper-Nelligan** [tanujdargan/uvic-coursemap#5]
I noticed that for the CSC 413 lab sections, the instructor says TBA, but the RateMyProf section still exists and links to a random prof from another university. I feel like if the instructor is TBA, there shouldn't be a RateMyProf section

**Comment by tanujdargan** [comment]
In theory, this issue should never occur as the graphQL API that ratemyprof uses requires a specific school ID in base64 form so it shouldn't be possible to get results from a different university. However, I do see the issue and have fixed it.

In this commit: https://github.com/tanujdargan/uvic-coursemap/commit/5b5f4ef8f1ffd74dbfe0cf9a19a8f70ff7a2e6af
